global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: soc-lab

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: wazuh-indexer
    metrics_path: /_prometheus/metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      username: admin
      password: SecretPassword
    static_configs:
      - targets: ["wazuh.indexer:9200"]

  - job_name: node
    static_configs:
      - targets: ["node-exporter:9100"]

  # Suricata stats endpoint (requires stats.enabled in suricata.yaml)
  - job_name: suricata
    static_configs:
      - targets: ["suricata:9555"]
